/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : Tacometer_Capture.h
**     Project     : Input_Capture
**     Processor   : MKL25Z128VLK4
**     Component   : Capture_LDD
**     Version     : Component 01.010, Driver 01.02, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-04-03, 18:56, # CodeGen: 47
**     Abstract    :
**          This component "Capture_LDD" simply implements the capture function
**          of timer. The counter counts the same way as in free run mode. On
**          the selected edge of the input signal (on the input pin), the current
**          content of the counter register is written into the capture
**          register and the OnCapture event is called.
**          This Capture component provides a high level API for unified
**          hardware access to various timer devices using the TimerUnit
**          component.
**     Settings    :
**          Component name                                 : Tacometer_Capture
**          Capture device                                 : TPM0_C3V
**          Counter                                        : TPM0_CNT
**          Counter direction                              : Up
**          Counter width                                  : 16 bits
**          Value type                                     : Optimal
**          Interrupt service/event                        : Enabled
**            Interrupt                                    : INT_TPM0
**            Interrupt priority                           : high priority
**          Event                                          : 
**            Input pin                                    : PTD3/SPI0_MISO/UART2_TX/TPM0_CH3/SPI0_MOSI
**            Input pin signal                             : Tacometer_Capture_Signal
**            Edge                                         : rising edge
**            Maximum time of event                        : 400 ms
**          Initialization                                 : 
**            Enabled in init. code                        : yes
**            Auto initialization                          : no
**            Event mask                                   : 
**              OnCapture                                  : Enabled
**              OnOverrun                                  : Disabled
**          CPU clock/configuration selection              : 
**            Clock configuration 0                        : This component enabled
**            Clock configuration 1                        : This component disabled
**            Clock configuration 2                        : This component disabled
**            Clock configuration 3                        : This component disabled
**            Clock configuration 4                        : This component disabled
**            Clock configuration 5                        : This component disabled
**            Clock configuration 6                        : This component disabled
**            Clock configuration 7                        : This component disabled
**          Referenced components                          : 
**            Linked TimerUnit                             : TU2
**     Contents    :
**         Init              - LDD_TDeviceData* Tacometer_Capture_Init(LDD_TUserData *UserDataPtr);
**         Enable            - LDD_TError Tacometer_Capture_Enable(LDD_TDeviceData *DeviceDataPtr);
**         Disable           - LDD_TError Tacometer_Capture_Disable(LDD_TDeviceData *DeviceDataPtr);
**         Reset             - LDD_TError Tacometer_Capture_Reset(LDD_TDeviceData *DeviceDataPtr);
**         GetCaptureValue   - LDD_TError Tacometer_Capture_GetCaptureValue(LDD_TDeviceData *DeviceDataPtr,...
**         SelectCaptureEdge - LDD_TError Tacometer_Capture_SelectCaptureEdge(LDD_TDeviceData...
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file Tacometer_Capture.h
** @version 01.02
** @brief
**          This component "Capture_LDD" simply implements the capture function
**          of timer. The counter counts the same way as in free run mode. On
**          the selected edge of the input signal (on the input pin), the current
**          content of the counter register is written into the capture
**          register and the OnCapture event is called.
**          This Capture component provides a high level API for unified
**          hardware access to various timer devices using the TimerUnit
**          component.
*/         
/*!
**  @addtogroup Tacometer_Capture_module Tacometer_Capture module documentation
**  @{
*/         

#ifndef __Tacometer_Capture_H
#define __Tacometer_Capture_H

/* MODULE Tacometer_Capture. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */
#include "TU2.h"

#include "Cpu.h"

#ifdef __cplusplus
extern "C" {
#endif 


#ifndef __BWUserType_Tacometer_Capture_TValueType
#define __BWUserType_Tacometer_Capture_TValueType
  typedef uint32_t Tacometer_Capture_TValueType ; /* Type for data parameters of methods */
#endif

#define Tacometer_Capture_CNT_INP_FREQ_U TU2_CNT_INP_FREQ_U_0 /* Counter input frequency in Hz */
#define Tacometer_Capture_CNT_INP_FREQ_R TU2_CNT_INP_FREQ_R_0 /* Counter input frequency in Hz */
#define Tacometer_Capture_COUNTER_WIDTH 0x10U /* Counter width in bits  */
#define Tacometer_Capture_COUNTER_DIR DIR_UP /* Direction of counting */
/*! Peripheral base address of a device allocated by the component. This constant can be used directly in PDD macros. */
#define Tacometer_Capture_PRPH_BASE_ADDRESS  0x40038000U
  
/* Methods configuration constants - generated for all enabled component's methods */
#define Tacometer_Capture_Init_METHOD_ENABLED /*!< Init method of the component Tacometer_Capture is enabled (generated) */
#define Tacometer_Capture_Enable_METHOD_ENABLED /*!< Enable method of the component Tacometer_Capture is enabled (generated) */
#define Tacometer_Capture_Disable_METHOD_ENABLED /*!< Disable method of the component Tacometer_Capture is enabled (generated) */
#define Tacometer_Capture_Reset_METHOD_ENABLED /*!< Reset method of the component Tacometer_Capture is enabled (generated) */
#define Tacometer_Capture_GetCaptureValue_METHOD_ENABLED /*!< GetCaptureValue method of the component Tacometer_Capture is enabled (generated) */
#define Tacometer_Capture_SelectCaptureEdge_METHOD_ENABLED /*!< SelectCaptureEdge method of the component Tacometer_Capture is enabled (generated) */

/* Events configuration constants - generated for all enabled component's events */
#define Tacometer_Capture_OnCapture_EVENT_ENABLED /*!< OnCapture event of the component Tacometer_Capture is enabled (generated) */



/*
** ===================================================================
**     Method      :  Tacometer_Capture_Init (component Capture_LDD)
*/
/*!
**     @brief
**         Initializes the device. Allocates memory for the device data
**         structure, allocates interrupt vectors and sets interrupt
**         priority, sets pin routing, sets timing, etc. If the
**         property ["Enable in init. code"] is set to "yes" value then
**         the device is also enabled (see the description of the
**         [Enable] method). In this case the [Enable] method is not
**         necessary and needn't to be generated. This method can be
**         called only once. Before the second call of Init the [Deinit]
**         must be called first.
**     @param
**         UserDataPtr     - Pointer to the user or
**                           RTOS specific data. This pointer will be
**                           passed as an event or callback parameter.
**     @return
**                         - Pointer to the dynamically allocated private
**                           structure or NULL if there was an error.
*/
/* ===================================================================*/
LDD_TDeviceData* Tacometer_Capture_Init(LDD_TUserData *UserDataPtr);

/*
** ===================================================================
**     Method      :  Tacometer_Capture_Enable (component Capture_LDD)
*/
/*!
**     @brief
**         Enables the component - the external events are counted.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - The component does not work in
**                           the active clock configuration
*/
/* ===================================================================*/
LDD_TError Tacometer_Capture_Enable(LDD_TDeviceData *DeviceDataPtr);

/*
** ===================================================================
**     Method      :  Tacometer_Capture_Disable (component Capture_LDD)
*/
/*!
**     @brief
**         Disables the component - the external events are not counted.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - The component does not work in
**                           the active clock configuration
*/
/* ===================================================================*/
LDD_TError Tacometer_Capture_Disable(LDD_TDeviceData *DeviceDataPtr);

/*
** ===================================================================
**     Method      :  Tacometer_Capture_Reset (component Capture_LDD)
*/
/*!
**     @brief
**         This method resets the counter register (see implementation
**         note in [General Info]).
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active clock configuration
*/
/* ===================================================================*/
LDD_TError Tacometer_Capture_Reset(LDD_TDeviceData *DeviceDataPtr);

/*
** ===================================================================
**     Method      :  Tacometer_Capture_GetCaptureValue (component Capture_LDD)
*/
/*!
**     @brief
**         This method gets the last value captured by enabled timer
**         (see implementation note in [General Info]). The method does
**         not return valid value after initialization or after [Reset]
**         until new capture event (even if the returned Error code is
**         ERR_OK).
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         ValuePtr        - A pointer to the content of the
**                           capture register
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active clock configuration
*/
/* ===================================================================*/
LDD_TError Tacometer_Capture_GetCaptureValue(LDD_TDeviceData *DeviceDataPtr, Tacometer_Capture_TValueType *ValuePtr);

/*
** ===================================================================
**     Method      :  Tacometer_Capture_SelectCaptureEdge (component Capture_LDD)
*/
/*!
**     @brief
**         Sets the type of edge for input capture.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         Edge            - Select type of edge for input capture
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_NOTAVAIL -  Action is not possible on
**                           selected device..
**                           ERR_SPEED - The component does not work in
**                           the active clock configuration
*/
/* ===================================================================*/
LDD_TError Tacometer_Capture_SelectCaptureEdge(LDD_TDeviceData *DeviceDataPtr, LDD_TimerUnit_TEdge Edge);

/*
** ===================================================================
**     Method      :  Tacometer_Capture_TU2_OnChannel2 (component Capture_LDD)
**
**     Description :
**         The method services the event of the linked component TU2 and 
**         eventually invokes event Tacometer_Capture_OnCapture.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void TU2_OnChannel2(LDD_TUserData *UserDataPtr);

/* END Tacometer_Capture. */

#ifdef __cplusplus
}  /* extern "C" */
#endif 

#endif 
/* ifndef __Tacometer_Capture_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
